In [1]:
import numpy as np

In [2]:
arr=np.array{[1,2,3,4]}

SyntaxError: invalid syntax (869343512.py, line 1)

In [3]:
arr=np.array{[1,2,3,4]}
print(arr)

SyntaxError: invalid syntax (1379018460.py, line 1)

In [4]:
arr=np.array([1,2,3,4])
print(arr)


[1 2 3 4]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

1

In [7]:
arr2d=np.array([1,2,3],[4,5,6],[7,8,9])
print(arr2d)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
arr2d.ndim

2

In [10]:
arr2d.size()

TypeError: 'int' object is not callable

In [11]:
arr2d.size

9

In [12]:
arr2d.shape

(3, 3)

In [13]:
arr.shape

(4,)

In [14]:
arr2d.dtype

dtype('int32')